### ISSUE TITLE
Rolling in critical fixes for downstream

### ISSUE THREAD

**Issue by cgwalters** [CentOS/sig-atomic-buildscripts#171]
I think https://rhn.redhat.com/errata/RHSA-2016-2110.html is critical enough that we should do an update, even if upstream hasn't necessarily done one.

**Comment by kbsingh** [comment]
+1

**Comment by jasonbrooks** [comment]
+1 @kbsingh will you update the tree?

@cgwalters should we update our images, as well?

**Comment by cgwalters** [comment]
I would argue for image updates, yes.  But let's get the updated tree out at a minimum.

**Comment by cgwalters** [comment]
Specifically, we want to pick up `kernel-3.10.0-327.36.3.el7.x86_64`

**Comment by cgwalters** [comment]
If there is anything at all I can do to help with this, please ping.  Am available for high bandwidth phone call/bluejeans/etc. if necessary.

**Comment by jasonbrooks** [comment]
I did a test build in the CI today, but only @kbsingh can update the official tree

**Comment by jasonbrooks** [comment]
This was fixed with `Version: 7.20161104 (2016-11-04 22:53:08)`
