### ISSUE TITLE
CAHC: need newer version of docker due to SELinux problems

### ISSUE THREAD

**Issue by miabbott** [CentOS/sig-atomic-buildscripts#178]
Recent composes of CAHC have this error in the logs:

```
libsemanage.semanage_direct_install_info: Overriding docker module at lower priority 100 with module at priority 400.
15:13:49 Re-declaration of boolean virt_sandbox_use_fusefs
15:13:49 Failed to create node
15:13:49 Bad boolean declaration at /etc/selinux/targeted/tmp/modules/100/virt/cil:159
15:13:49 /usr/sbin/semodule:  Failed!
```

This seems to arise from the version of `selinux-policy-targeted` that is being pulled in from the CentOS-CR repo.

@cgwalters suggested on IRC to use a newer version of `docker` to mitigate this.

Not sure which version to use...maybe something from [projectatomic/docker](https://github.com/projectatomic/docker/)?

**Comment by cgwalters** [comment]
Alternatively we might be able to drop out the virt-sig docker in favor of the Core rebuild.

**Comment by cgwalters** [comment]
Unfortunately, we can't easily do that as there's no repos for extras/rhel-atomic-rebuild that I'm aware of that use CR.  I could do it of course, but CentOS will need to do it anyways, so we should ping them.

**Comment by jasonbrooks** [comment]
May not be worth messing w/ any further, but I did a test build w/ these excludes: https://github.com/CentOS/sig-atomic-buildscripts/pull/182

**Comment by cgwalters** [comment]
This is fixed (for now anyways).
