### ISSUE TITLE
Fixate uid/gids

### ISSUE THREAD

**Issue by cgwalters** [CentOS/sig-atomic-buildscripts#18]
See 
https://bugzilla.redhat.com/show_bug.cgi?id=1203006
https://git.fedorahosted.org/cgit/fedora-atomic.git/commit/?id=debbecbc6cec7ae494f26703d0ae28b2c53b0e26

This is not an emergency for CentOS as the latest rpm-ostree will automatically do this *given a previous commit* - but it means freshly composed trees may be subject to drift.

**Comment by cgwalters** [comment]
@imcleod has gathered the uid/gid mapping from upstream here: https://github.com/imcleod/sig-atomic-buildscripts/tree/scratch/rhel-snapshot/rhel-scratch-snapshot

We should consider a one-time break and do this for the SIG build as well.

**Comment by jasonbrooks** [comment]
We got this back at commit cd60e83
