### ISSUE TITLE
rpm-ostree install fails running post

### ISSUE THREAD

**Issue by mike-nguyen** [CentOS/sig-atomic-buildscripts#192]
[cloud-user@cloud-6 ~]$ sudo rpm-ostree status
State: idle
Deployments:
● centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
       Version: 7.2016.1087 (2016-12-05 17:23:23)
        Commit: 5bc514a4b818aaf7b4da43721796577ca790bab6ab7b141e5909ca84bdc5a226
        OSName: centos-atomic-host
 
  centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
       Version: 7.2016.71 (2016-08-23 13:09:11)
        Commit: 4df97c9e62f711f26c5b6f92607fbbd32df89223edb2678a54a87f67ec36d86f
        OSName: centos-atomic-host
[cloud-user@cloud-6 ~]$ sudo rpm-ostree install wget
Checking out tree 5bc514a... done
 
Downloading metadata: [========================================================================================] 100%
Resolving dependencies... done
Overlaying... done
Running %post for wget...... error: Running %post for wget: Executing bwrap: Child process exited with code 1

**Comment by mike-nguyen** [comment]
@walters stated this is likely a regression from https://github.com/projectatomic/bubblewrap/pull/122

**Comment by cgwalters** [comment]
Should be fixed by https://github.com/projectatomic/bubblewrap/pull/123

**Comment by cgwalters** [comment]
Looks like this is fixed to me.
