### ISSUE TITLE
NetworkManager unable to create /etc/resolv.conf; SELinux denial

### ISSUE THREAD

**Issue by miabbott** [CentOS/sig-atomic-buildscripts#195]
We hadn't seen this when booting an older version of the CAHC cloud image (7.2016.834) and then deploying the newer commits.  However, once the cloud-image job was fixed (see #194), the internal CAHC tests started to fail at the provisioning stage.

The initial error was was related to pulling the commit metadata:

```
failed: [10.8.169.180] => {"changed": true, "cmd": ["ostree", "pull", "--commit-metadata-only", "--depth=1", "centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous"], "delta": "0:00:00.280108", "end": "2016-12-09 13:18:30.029410", "rc": 1, "start": "2016-12-09 13:18:29.749302", "warnings": []}
08:18:46 stderr: error: Error resolving 'ci.centos.org': Name or service not known
```

However, further investigation points to an empty `/etc/resolv.conf`.  The following messages are seen in the journal:

```
Dec 08 20:46:00 rhel-atomic-7 kernel: type=1400 audit(1481229960.565:5): avc:  denied  { create } for  pid=717 comm="NetworkManager" name="resolv.conf.IBFURY" scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:etc_t:s0 tclass=file
Dec 08 20:46:00 rhel-atomic-7 NetworkManager[717]: <warn>  [1481229960.5715] dns-mgr: could not commit DNS changes: Failed to create file '/etc/resolv.conf.IBFURY': Permission denied
```

This was originally reported in the internal #atomic channel by @p3ck

**Comment by cgwalters** [comment]
Dup of https://github.com/CentOS/sig-atomic-buildscripts/issues/191 I think.

**Comment by miabbott** [comment]
Oh dang, it is.  😞

**Comment by pasckoch** [comment]
Same problem in 2024, rights error on temporary file /etc/resolv.com.XXXXX at startup NetworkManager service, quick fix : rm -fr /etc/resolv.conf && service NetworkManager restart
