### ISSUE TITLE
RFC: Add a new 'smoketested' branch

### ISSUE THREAD

**Issue by jlebon** [CentOS/sig-atomic-buildscripts#227]
As described in [the ostree manual](http://ostree.readthedocs.io/en/latest/manual/repository-management/#promoting-content-along-ostree-branches-buildmaster-smoketested), it would be interesting to have a new "smoketested" branch based off of the continuous branch gated on tests.

Ideally, these tests would run in the CentOS CI as well. However, because we cannot currently very easily provision Atomic Hosts in the CI infra, I propose that for now, we make use of the automated tests done by the internal Red Hat Jenkins. These jobs run the [improved-sanity-test](https://github.com/projectatomic/atomic-host-tests/tree/master/tests/improved-sanity-test) on every new continuous commit.

An easy way to implement this workflow would be to automatically push a new `smoketested` tag to the `releases.yml` file whenever such a test passes. Once better support for Atomic Host provisioning is added directly in the CentOS CI, we can look into migrating the testers there.

**Comment by cgwalters** [comment]
We can install libvirt though and do VM based testing easily enough.

**Comment by jlebon** [comment]
Do you know when Atomic Host provisioning will be available? I was under the impression that it was coming Really Soon (tm), which is why I was leaning towards the easy way for now and the proper way later. Nested work would require some work to get right, but if we're OK with it being a more long-term solution, then we can go that route.

**Comment by cgwalters** [comment]
Remember the awesome thing about CentOS CI is that duffy is bare metal provisioning, so if we do virt it won't be nested.

**Comment by cgwalters** [comment]
That fact is why our ImageFactory runs in CentOS CI are fast.

**Comment by jlebon** [comment]
Oh silly me, I absolutely did not realize Duffy was bare metal. Even though, now that I look at it, it's in the very first sentence on https://wiki.centos.org/QaWiki/CI/Duffy. That's pretty sweet.
