### ISSUE TITLE
centos-release-atomic patch

### ISSUE THREAD

**Issue by jasonbrooks** [CentOS/sig-atomic-buildscripts#239]
The current, downstream-7.20170117, release of centos atomic is subject to this issue with rpm-ostree package layering: https://bugzilla.redhat.com/show_bug.cgi?id=1399770 

The upcoming downstream release includes rpm-ostree-client-2016.13-1.atomic.el7.x86_64, and doesn't have this issue, but @cgwalters has suggested that we adopt a patch similar to https://bugzilla.redhat.com/show_bug.cgi?id=1399770#c2 for centos-release-atomic. 

Colin's patch puts `os-release` into `/usr/lib/` and symlinks that to `/etc/`. One potential issue here is that centos-release-atomic depends on centos-release, and that's where our `os-release` comes from. https://git.centos.org/blob/rpms!centos-release-atomic/b132798c53c3ebe5544790053b59af19529307c1/SPECS!centos-release-atomic.spec

@kbsingh Should we adopt a release pkg approach similar to rhel, I don't recall all the reasons for doing this the way we have?

**Comment by cgwalters** [comment]
It's likely simpler to backport the fix: https://github.com/rpm-software-management/libdnf/pull/215

Or bump to the latest rpm-ostree.

**Comment by jlebon** [comment]
Any news on this? A lot of people are hitting this issue.
@jasonbrooks How hard would it be to backport the libdnf patch?

**Comment by jasonbrooks** [comment]
Just waiting on @kbsingh to rsync the updated tree into place.

**Comment by jasonbrooks** [comment]
It looks like the new tree is in place now:

```
centos-atomic-host:centos-atomic-host/7/x86_64/standard
       Version: 7.20170209 (2017-02-10 00:54:47)
        Commit: d433342b09673c9c4d75ff6eef50a447e73a7541491e5197e1dde14147b164b8
```

I'll send out an announcement today

**Comment by cgwalters** [comment]
Ok, let's mark as done.  Thanks for all your work on this @jasonbrooks !
