### ISSUE TITLE
CAHC: docker returning 'Unknown runtime specified oci' starting existing containers

### ISSUE THREAD

**Issue by miabbott** [CentOS/sig-atomic-buildscripts#265]
Our automated tests failed when running `atomic run` on an existing container in CAHC `7.2017.268`:

https://s3.amazonaws.com/aos-ci/atomic-host-tests/improved-sanity-test/cahc/latest/improved-sanity-test.log

The output was not enough to pin down the reason, so I reproduced manually and saw the following:

```
# docker start centos_httpd
Error response from daemon: Unknown runtime specified oci
Error: failed to start containers: centos_httpd
```

The test built the `centos_httpd` container using the version (`1.12.6-14.gitf499e8b.el7`) of `docker` in CAHC `7.2017.267` and then after the upgrade, we see this error.  The newer version of `docker` is `1.12.6-16.el7`.

The treecompose for this versions seems to indicate that `docker` is now coming from `CentOS-extras`

https://ci.centos.org/job/atomic-treecompose-centos7/6819/console

Previously, it was coming from `virt7-docker-common-candidate`

https://ci.centos.org/job/atomic-treecompose-centos7/6818/console

**Comment by mike-nguyen** [comment]
This is the archived log: https://s3.amazonaws.com/aos-ci/atomic-host-tests/improved-sanity-test/cahc/jenkins-atomic-host-jobs-treecompose-improved-sanity-test-cahc-260/improved-sanity-test.log

**Comment by lsm5** [comment]
let me try to get a new docker built for virt sig

**Comment by lsm5** [comment]
check how this works https://cbs.centos.org/koji/taskinfo?taskID=176770

**Comment by miabbott** [comment]
@lsm5 Looks like there are some unresolved dependencies:

```
# ls -l *rpm
-rw-r--r--. 1 root root 27517656 Apr 21 16:31 docker-1.13.1-9.git14cc629.el7.x86_64.rpm
-rw-r--r--. 1 root root    73656 Apr 21 16:31 docker-common-1.13.1-9.git14cc629.el7.x86_64.rpm
-rw-r--r--. 1 root root    72900 Apr 21 16:31 docker-logrotate-1.13.1-9.git14cc629.el7.x86_64.rpm
-rw-r--r--. 1 root root  2293532 Apr 21 16:31 docker-lvm-plugin-1.13.1-9.git14cc629.el7.x86_64.rpm
-rw-r--r--. 1 root root  2024400 Apr 21 16:31 docker-novolume-plugin-1.13.1-9.git14cc629.el7.x86_64.rpm
-rw-r--r--. 1 root root  2115356 Apr 21 16:31 docker-rhel-push-plugin-1.13.1-9.git14cc629.el7.x86_64.rpm
-rw-r--r--. 1 root root    58652 Feb  7 17:29 fuse-sshfs.rpm
# ostree admin unlock
Development mode enabled.  A writable overlayfs is now mounted on /usr.
All changes there will be discarded on reboot.
# rpm -Uhv docker-1.13.1-9.git14cc629.el7.x86_64.rpm docker-common-1.13.1-9.git14cc629.el7.x86_64.rpm docker-lvm-plugin-1.13.1-9.git14cc629.el7.x86_64.rpm docker-novolume-plugin-1.13.1-9.git14cc629.el7.x86_64.rpm docker-rhel-push-plugin-1.13.1-9.git14cc629.el7.x86_64.rpm
error: Failed dependencies:
	container-storage-setup is needed by docker-2:1.13.1-9.git14cc629.el7.x86_64
	parted is needed by docker-2:1.13.1-9.git14cc629.el7.x86_64
```

I couldn't find a build of `container-storage-setup` in CBS and the requirement on `parted` is a new one.

**Comment by miabbott** [comment]
Old issue is old and fixed
