### ISSUE TITLE
redirect alpha → smoketested

### ISSUE THREAD

**Issue by cgwalters** [CentOS/sig-atomic-buildscripts#269]
Per consensus in SIG Atomic meeting, drop the Alpha branch and redirect it to `/smoketested`.

**Comment by jlebon** [comment]
Right, I guess that makes more sense than dropping `smoketested` and making the smoketester update `alpha` directly.

**Comment by cgwalters** [comment]
Ohh, hm a wrinkle in this is there's no images for smoketested.

**Comment by cgwalters** [comment]
Eh.  It's OK for now with me if most users of this start from CAH-release.

**Comment by cgwalters** [comment]
PR in https://github.com/CentOS/sig-atomic-buildscripts/pull/270

**Comment by cgwalters** [comment]
And I updated https://wiki.centos.org/SpecialInterestGroup/Atomic/Devel
