### ISSUE TITLE
CAHC rdgo blocked on systemd/dracut issue

### ISSUE THREAD

**Issue by jlebon** [CentOS/sig-atomic-buildscripts#299]
Just logging this here to have some place to discuss.

https://ci.centos.org/job/atomic-rdgo-centos7/22714/console

> 12:38:13  --> systemd-devel-219-42.el7_4.1.x86_64
> 12:38:13  --> gobject-introspection-devel-1.50.0-1.el7.x86_64
> 12:38:13  --> dracut-033-361.el7.centos.2.x86_64
> 12:38:13  --> bison-3.0.4-1.el7.x86_64
> 12:38:17 Error: systemd conflicts with dracut-033-361.el7.centos.2.x86_64

**Comment by cgwalters** [comment]
PR in https://github.com/CentOS/sig-atomic-buildscripts/pull/300 (not yet tested locally but in progress)
