### ISSUE TITLE
Builds failing due to missing updated dependency

### ISSUE THREAD

**Issue by citizentim** [CentOS/sig-atomic-buildscripts#303]
At sometime during the day today, my ISO builds using sig-atomic-buildscripts have begun to fail during build_stage2.sh during:

rpm-ostree-toolbox installer --overwrite --ostreerepo ${BuildDir}/repo -c  ${GitDir}/config.ini -o ${BuildDir}/installer |& tee ${LogFile}

The error is 

> (  0/  0) [100%] downloading yum-utils-1.1.31-42.el7.noarch.rpm
> (  0/  0) [100%] downloading zlib-1.2.7-17.el7.x86_64.rpm
> (  0/  0) [100%] downloading zenity-3.22.0-1.el7.x86_64.rpm
> checking package signatures
> running test transaction
> 2017-10-24 21:28:55,766: template command error in runtime-install.tmpl:
> template command error in runtime-install.tmpl:
> 2017-10-24 21:28:55,767:   run_pkg_transaction
>   run_pkg_transaction
> 2017-10-24 21:28:55,772:   YumRPMCheckError: [u'ERROR with transaction check vs depsolve:', 'libostree-1.so.1(LIBOSTREE_2017.10)(64bit) is needed by rpm-ostree-libs-2017.9-2.atomic.el7.x86_64', 'libostree-1.so.1(LIBOSTREE_2017.10)(64bit) is needed by rpm-ostree-2017.9-2.atomic.el7.x86_64', 'libostree-1.so.1(LIBOSTREE_2017.7)(64bit) is needed by rpm-ostree-2017.9-2.atomic.el7.x86_64']
>   YumRPMCheckError: [u'ERROR with transaction check vs depsolve:', 'libostree-1.so.1(LIBOSTREE_2017.10)(64bit) is needed by rpm-ostree-libs-2017.9-2.atomic.el7.x86_64', 'libostree-1.so.1(LIBOSTREE_2017.10)(64bit) is needed by rpm-ostree-2017.9-2.atomic.el7.x86_64', 'libostree-1.so.1(LIBOSTREE_2017.7)(64bit) is needed by rpm-ostree-2017.9-2.atomic.el7.x86_64']

It appears that the buildlogs repo at https://buildlogs.centos.org/centos/7/atomic/x86_64/Packages has been updated today but is missing new ostree packages which correspond to  rpm-ostree-libs-2017.9-2.atomic.el7.x86_64.  This is a big deal for us as we can't build our release (I should've created a local mirror, doh!)

Apologies if this is not the correct forum to report this.

Thanks in advance

**Comment by jasonbrooks** [comment]
I'm actually experiencing this, too. I'm looking into it now.

**Comment by citizentim** [comment]
I'd just clone the repo and remove yesterday's updates as a workaround, but all previous versions of rpm-ostree-libs have been removed from the repo.

I'm wondering if you were able to make any headway?  This is a mission-critical problem for us.

**Comment by citizentim** [comment]
The problem can be worked around by cloning the buildlogs repo and manually adding the missing updated ostree dependencies from http://cbs.centos.org/koji/buildinfo?buildID=19369.

The public buildlogs repo just needs to have those newer ostree packages added to it.

**Comment by jasonbrooks** [comment]
4730d470 got me past this, but then I hit another issue later in the script.

**Comment by jasonbrooks** [comment]
@citizentim This should be working again now
