### ISSUE TITLE
qcow2 generation for CAHC has been failing for about 25 days

### ISSUE THREAD

**Issue by miabbott** [CentOS/sig-atomic-buildscripts#333]
I noticed the version of  `centos/7/atomic/continuous` image on our internal OpenStack instance was last updated on May 9.  Lo and behold, the cloud-image job has been failing for about that long.

Looks like the `oz` process is timing out.  I don't have access to the workspace/screenshot, so I don't know what is really happening there.

https://ci.centos.org/job/atomic-cahc-image-cloud-continuous/3969/console

```
13:33:30 Exception encountered in _build_image_from_template thread
13:33:30 No disk activity in 300 seconds, failing.  Check screenshot at /var/lib/oz/screenshots/factory-build-9d3f94ce-5ab9-4ee4-8b9e-dc31782ccebb-1528119210.08.ppm for more detail
13:33:30 Traceback (most recent call last):
13:33:30   File "/usr/lib/python2.7/site-packages/imgfac/Builder.py", line 132, in _build_image_from_template
13:33:30     self.os_plugin.create_base_image(self, template, parameters)
13:33:30   File "/usr/lib/python2.7/site-packages/imagefactory_plugins/TinMan/TinMan.py", line 346, in create_base_image
13:33:30     libvirt_xml = self.guest.install(self.app_config["timeout"])
13:33:30   File "/usr/lib/python2.7/site-packages/oz/RedHat.py", line 705, in install
13:33:30     self.initrdfname, self.cmdline)
13:33:30   File "/usr/lib/python2.7/site-packages/oz/Guest.py", line 1714, in _do_install
13:33:30     self._wait_for_install_finish(dom, timeout)
13:33:30   File "/usr/lib/python2.7/site-packages/oz/Guest.py", line 829, in _wait_for_install_finish
13:33:30     raise oz.OzException.OzException("No disk activity in %d seconds, failing.  %s" % (inactivity_timeout, screenshot_text))
13:33:30 OzException: No disk activity in 300 seconds, failing.  Check screenshot at /var/lib/oz/screenshots/factory-build-9d3f94ce-5ab9-4ee4-8b9e-dc31782ccebb-1528119210.08.ppm for more detail
```

cc: @jlebon @mike-nguyen

**Comment by jlebon** [comment]
As a first step to debugging this, I added screenshot archiving in #334.

**Comment by miabbott** [comment]
OK, from the latest failure...

https://ci.centos.org/job/atomic-cahc-image-cloud-continuous/4012/

The screen shot from the console captured messages about `dracut-initqueue timeout - starting timeout scripts` and `Warning: /dev/root does not exist`

Eventually the host drops to the `dracut` shell.

@jlebon any ideas?

**Comment by jlebon** [comment]
Well, that's not a very useful screenshot. :) It's likely the key to the error happened way back off the screen. Would be nice if we could extract `rdsosreport.txt` as well.

Anyway, probably the easiest way to debug this for now is to just try to reproduce it locally.

**Comment by miabbott** [comment]
> Anyway, probably the easiest way to debug this for now is to just try to reproduce it locally.

I'll see if I can acheive that

**Comment by miabbott** [comment]
I setup a Fedora 28 host in the internal OpenStack instance to test this out.  I was able to reproduce the failure; the logs appear to indicate that the `dracut-initqueue` is running a `curl` command that ultimately fails. 

![screenshot from 2018-06-11 13-31-45](https://user-images.githubusercontent.com/10236257/41247473-10417128-6d7c-11e8-9993-70bd56cd04db.png)

 Hard to say for sure if this is the same reason why the Jenkins job is failing, though.

I definitely don't know enough about what `rpm-ostree-toolbox`/`oz`/`dracut` is trying to do here.

**Comment by miabbott** [comment]
> What is your memory value in /etc/oz/oz.cfg set to? 

Ohhhhhhh.... I remember now that I should have bumped this based on previous conversations regarding `oz`....yup, still 1024

Will bump it and see what happens.

**Comment by miabbott** [comment]
Bumped the memory to 3G and re-ran `run-image-cloud` on the VM, but the whole system died due to a kernel panic...

I'm using a m1.medlarge flavor...maybe it needs even more RAM?  Or real hardware...

Anyways, I'm going to punt on reproducing this for the day.  I'll give it another go tomorrow.

**Comment by jlebon** [comment]
This is fixed now! :tada:
https://ci.centos.org/artifacts/sig-atomic/centos-continuous/images/cloud/

Thanks for investigating Micah!

**Comment by miabbott** [comment]
Woo!  Great job with the fixes @jlebon!
