### ISSUE TITLE
Need a clean way in my script to figure out that its running on atomic

### ISSUE THREAD

**Issue by parthaa** [CentOS/sig-atomic-buildscripts#61]
I have a bash script that needs to do something along the lines of
```
if <running on atomic>
then
 <setup these entries>
else
 #running on standard rhel/centos
  <setup alternate entries>
fi
```
And this script needs to run in 2 places
1) During provisioning a Centos/Rhel atomic os  as a part of the KS post script
2) Standalone on the machine  after it has booted . Because the user may choose to run it on an existing instance.

Given i need a way in centos to figure out that its running on atomic machine.
I cannot do ``[ -e "/run/ostree-booted"] `` as suggested in forums for Case 1 because during provisioning this directory does not exist on an atomic machine. 
Any ideas?

For a rhel machine I can do something  along the lines of
```
grep -i "Atomic Host" /etc/os-release 
if [ $? -eq 0 ]
then
 <setup atomic entries>
else
 #running on standard rhel/centos
  <setup alternate entries>
fi

```

But for centos I cannot get that information because the /etc/os-release looks like

```

[centos@cloud ~]$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

References:
https://bugzilla.redhat.com/show_bug.cgi?id=1200122

**Comment by jasonbrooks** [comment]
@parthaa I want to understand your use case better -- you want to detect whether a machine is running centos atomic, but detect this before the machine is running? Or before the atomic tree is installed? The kubenetes/contrib ansible scripts (https://github.com/kubernetes/contrib/tree/master/ansible), look for `/run/ostree-booted`. I see that you've said that this doesn't exist during provisioning, but if you're opting to provision a system with centos atomic, where's the need to detect?

**Comment by cgwalters** [comment]
Considering this fixed by https://github.com/projectatomic/centos-release-atomic-host-devel/commit/529c480d04f4c8c007e631514a274f6ab412dff3
which is now in the latest CAHC.
