### ISSUE TITLE
Issue with vir7 repo

### ISSUE THREAD

**Issue by brettau** [CentOS/sig-atomic-buildscripts#66]
[virt7-testing]
name=virt7-testing
baseurl=http://cbs.centos.org/repos/virt7-testing/x86_64/os/
gpgcheck=0
exclude=kernel docker

Should be http://cbs.centos.org/repos/virt7-common-testing/x86_64/os/

virt7-testing no longer exists

**Comment by jasonbrooks** [comment]
PR #67 addressed this, replacing virt7-testing w/ virt7-docker-common-candidate
